stages:
  - test
  - build
  - deploy

test-job:
  stage: test
  script:
    - mvn test

build-job:
  stage: build
  script:
    - docker build --network=host -t my-backend .

deploy-job:
  stage: deploy
  script:
    - docker compose up -d
